import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
/**
 * Font Configuration
 * Using Next.js Google Fonts optimization to load fonts locally.
 * We assign CSS variables so they can be accessed throughout our Tailwind config.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/**
 * Metadata Configuration
 * This defines the SEO headers for all pages. 
 * Updated to reflect your specific Ecommerce Dashboard project.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/**
 * Root Layout Component
 * This is the top-level wrapper for your entire application.
 * Any component here (like a Navbar or Footer) would appear on every page.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
